########## BASIC CONFIGURATIONS SETTINGS ############

DATA_SET = "had12.dat"
CROSSOVER_PERCENTAGE = 0.7
MUTATION_PERCENTAGE = 0.08
POPULATION_SIZE = 100
NUMBER_OF_GENERATIONS = 10
DRAW_VISUALIZATION = True
DRAW_GRAPH = True
